apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    name: auth
spec:
  type: LoadBalancer # this assumes you're exposing this service to the outside world
  ports:
    - name: auth
      port: 80 # this assumes you're exposing this service to the outside world
      targetPort: 9090
      protocol: TCP
  selector:
    role: backend
    app: auth
